### ISSUE TITLE
berryc on debian armv7 segfaults

### ISSUE THREAD

**Issue by reallyrandomuser** [JLErvin/berry#161]
Hello,

berryc on my Asus Chromebook c201 running Debian seems to segfault. Linked below is the coredump.

https://0x0.st/ozKS.bin

Is there something I've done wrong? I've installed all the dependencies included in the documentation. Thanks.

**Comment by sourTaste000** [comment]
I have the same issue, but I am on x86_64.
Here is the coredump:
```
❯ coredumpctl gdb berryc
           PID: 17006 (berryc)
           UID: 1000 (sourtaste000)
           GID: 1000 (sourtaste000)
        Signal: 11 (SEGV)
     Timestamp: Tue 2022-01-04 23:06:43 PST (35s ago)
  Command Line: berryc
    Executable: /usr/local/bin/berryc
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-Alacritty-774a002ec3124f7aaff23d89b940c619.scope
          Unit: user@1000.service
     User Unit: app-Alacritty-774a002ec3124f7aaff23d89b940c619.scope
         Slice: user-1000.slice
     Owner UID: 1000 (sourtaste000)
       Boot ID: 786de6a2ae37422ba2de9adc339626e1
    Machine ID: 1ddc2c5681f84fbbbaef04b9311fa87a
      Hostname: starfeesh
       Storage: /var/lib/systemd/coredump/core.berryc.1000.786de6a2ae37422ba2de9adc339626e1.17006.1641366403000000.zst (present)
     Disk Size: 98.4K
       Message: Process 17006 (berryc) of user 1000 dumped core.

                Module linux-vdso.so.1 with build-id 33391ff5d8b361d70dd5922e8d2b5c1b451401bb
                Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                Module libbrotlicommon.so.1 with build-id a4ba3f4b4571c8272343b621da812a6e24a202a7
                Module libglib-2.0.so.0 with build-id 8214b56e554b7cbead4034b6ba32c90bc8c674da
                Module libgraphite2.so.3 with build-id 47761dc11e553f519cde97ed9ee985be12ccdae2
                Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
                Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
                Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
                Module libXrender.so.1 with build-id 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                Module libbrotlidec.so.1 with build-id 45defc036e918e0140a72f1fbce6e7692d38241d
                Module libharfbuzz.so.0 with build-id 1d9dee49dd99162c3f83eb3259c3c88c6b4cd7fe
                Module libpng16.so.16 with build-id 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                Module libz.so.1 with build-id 0c1459c56513efd5d53eb3868290e9afee6a6a26
                Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
                Module libexpat.so.1 with build-id 16023a53e7b5bbdff92bd0bf2eebd36f9b5b879f
                Module libXext.so.6 with build-id d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
                Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
                Module libXft.so.2 with build-id 21aed1dfa73fa7301e280e3a573cc2523a1f7ff2
                Module libfreetype.so.6 with build-id 26c5f833068ff72660d1975cbc2074c3eb47fad8
                Module libfontconfig.so.1 with build-id 1103a641395c7d3b42e49b793d3a9ea927c77bf6
                Module libXinerama.so.1 with build-id dbb6adece34ea2766d3efcd628af8f9757344dd6
                Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
                Module berryc with build-id b8662d2b5d8b8f4f41a4ca5bd0f14b59c2c70168
                Stack trace of thread 17006:
                #0  0x00007f8ee6d63a0e __strcmp_avx2 (libc.so.6 + 0x15ba0e)
                #1  0x0000555591a2124e n/a (berryc + 0x224e)
                #2  0x00007f8ee6c2fb25 __libc_start_main (libc.so.6 + 0x27b25)
                #3  0x0000555591a2147e n/a (berryc + 0x247e)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/berryc...
(No debugging symbols found in /usr/local/bin/berryc)
[New LWP 17006]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `berryc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8ee6d63a0e in __strcmp_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f8ee6d63a0e in __strcmp_avx2 () from /usr/lib/libc.so.6
#1  0x0000555591a2124e in ?? ()
#2  0x00007f8ee6c2fb25 in __libc_start_main () from /usr/lib/libc.so.6
#3  0x0000555591a2147e in ?? ()
```

I have `libxinerama`, `libxft` and `libx11` installed.
